patchedDependencies:
  '@terrazzo/plugin-css': patches/@terrazzo__plugin-css.patch
  '@unpunnyfuns/swatchbook-addon': patches/@unpunnyfuns__swatchbook-addon.patch
  '@unpunnyfuns/swatchbook-blocks': patches/@unpunnyfuns__swatchbook-blocks.patch
